* It should have some categorical features. However, it does not need to only have categorical features -
a mix of categorical and continuous features is also fine.
* All features should either be categorical or numerical. This means that you shouldn’t choose a data
set where the observations are images, long blocks of texts, or other data types that would require
significant processing before applying machine algorithms (you’ll have the opportunity to work with
this type of data for Project 3).
* Your data set should be reasonably large.
Because you’ve already done a project on classification, I suggest that you try to do a project on regression,
but this is not a requirement.
I encourage you to look for your own data set (through the UCI repository, or other sources). If you’re
having trouble finding one that interests you, here are some suggestions:
* Bank Marketing Data Set. https://archive.ics.uci.edu/ml/datasets/Bank+Marketing
* Census Income Data Set. https://archive.ics.uci.edu/ml/datasets/Census+Income
* Contraceptive Method Choice Data Set. https://archive.ics.uci.edu/ml/datasets/Contraceptive+
Method+Choice
* Crimes in Chicago. https://www.kaggle.com/currie32/crimes-in-chicago
* Default of Credit Card Clients Data Set. https://archive.ics.uci.edu/ml/datasets/default+
of+credit+card+clients
* Mushroom Data Set. https://archive.ics.uci.edu/ml/datasets/Mushroom
* New York City Property Sales. https://www.kaggle.com/new-york-city/nyc-property-sales
* Online Shoppers Purchasing Intention Dataset. https://archive.ics.uci.edu/ml/datasets/Online+
Shoppers+Purchasing+Intention+Dataset
* Poker Hand Data Set. https://archive.ics.uci.edu/ml/datasets/Poker+Hand
* Synthetic Financial Datasets for Fraud Detection. https://www.kaggle.com/ntnu-testimon/paysim1
(actually a fake data set, but should still provide useful practice)
* Video Game Sales. https://www.kaggle.com/rush4ratio/video-game-sales-with-ratings
(continued on reverse)
Once you’ve chosen your data set, complete the following tasks.
Write a Plan. Before you start working with your data set, make a plan for the workflow of your project.
Write up this plan, and include it at the beginning of your Jupyter notebook. Once you start to work with
your data set, you might find that you need to deviate from your original plan, this is good! When this
happens, don’t make delete tasks from your original plan - just acknowledge that you encountered something
unexpected, and explain what adjustments will need to be made.
Your plan should include the following:
* What will be your goal in working with this data set?
* What data cleaning will you need to do to prepare the data set?
* What kinds of exploratory data analysis will you do?
* Which machine learning algorithms will you use to train models? Why are you choosing these algorithms?
* How will you attempt to optimize your models?
* How will you analyze the accuracy of your models? Approximately what do you think will be “good”
accuracy rates for your chosen task?
Preparing Your Data Set. Following the outline given in your plan, prepare your data set for training
using the methods we’ve discussed. This is likely to include handling missing values and categorical variables.
Any choices that you make should be explained.
Exploratory Data Analysis. Following the outline given in your plan, perform some exploratory data
analysis. Discuss the results, and what this means for the distribution of the data, as well as your expectations for your results. This should include multiple methods of data visualization.
Train Models Using Machine Learning Algorithms. Although you do not need to use every algorithm
that we’ve covered, you should use those that make sense for your data set. You should explain your choices,
and perform parameter tuning in order to optimize their performance.
Discussion of Results. Compare the performance of your models, and discuss their accuracy. Do you consider your results successful? Explain why or why not, and discuss how further improvements might be made.
Evaluation of Your Plan. Discuss how closely you were able to follow your initial plan. What unexpected
issues did you encounter? What adjustments did you need to make? How would this affect planning a future
machine learning project?
For this project, you will submit a Jupyter Notebook through moodle and give an in-class presentation on
Thursday, January 24th. In order to make sure that you’re on track, you should write your plan
prior to class on Monday, January 20th, so we can discuss it.

# Suicide Detection using Socio-Economic Metrics as Signals


The data and a description of the data can be found at 
https://www.kaggle.com/russellyates88/suicide-rates-overview-1985-to-2016.

Content:
    This compiled dataset pulled from four other datasets linked by time and place, and was built to find signals correlated to increased suicide rates among different cohorts globally, across the socio-economic spectrum.
    
References:

    - United Nations Development Program. (2018). Human development index (HDI). Retrieved from                                                 http://hdr.undp.org/en/indicators/137506
    http://hdr.undp.org/en/content/human-development-index-hdi

    - World Bank. (2018). World development indicators: GDP (current US$) by country:1985 to 2016. Retrieved from http://databank.worldbank.org/data/source/world-development-indicators#

    - [Szamil]. (2017). Suicide in the Twenty-First Century [dataset]. Retrieved from https://www.kaggle.com/szamil/suicide-in-the-twenty-first-century/notebook

    - World Health Organization. (2018). Suicide prevention. Retrieved from http://www.who.int/mental_health/suicide-prevention/en/

# Preprocessing

In [23]:
import pandas as pd

# load data from path into a dataframe
path = "master.csv"
df = pd.read_csv(path)

df.head()

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
0,Albania,1987,male,15-24 years,21,312900,6.71,Albania1987,NaN,"2,156,624,900",796,Generation X
1,Albania,1987,male,35-54 years,16,308000,5.19,Albania1987,NaN,"2,156,624,900",796,Silent
2,Albania,1987,female,15-24 years,14,289700,4.83,Albania1987,NaN,"2,156,624,900",796,Generation X
3,Albania,1987,male,75+ years,1,21800,4.59,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
4,Albania,1987,male,25-34 years,9,274300,3.28,Albania1987,NaN,"2,156,624,900",796,Boomers

The syntax of the features is not consistent. There are both underscores to fill in spaces and spaces. We will change the names of the features to make the accessing the data easier in the preprocessing.

In [24]:
df.rename(columns={"gdp_per_capita ($)": "gdp_per_capita", "gdp_for_year ($)": "gdp_for_year", 
                   "HDI for year": "HDI_for_year", "country-year": "country_year", 
                   "suicides/100k pop": "suicides/100k_pop"})

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
0,Albania,1987,male,15-24 years,21,312900,6.71,Albania1987,NaN,"2,156,624,900",796,Generation X
1,Albania,1987,male,35-54 years,16,308000,5.19,Albania1987,NaN,"2,156,624,900",796,Silent
2,Albania,1987,female,15-24 years,14,289700,4.83,Albania1987,NaN,"2,156,624,900",796,Generation X
3,Albania,1987,male,75+ years,1,21800,4.59,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
4,Albania,1987,male,25-34 years,9,274300,3.28,Albania1987,NaN,"2,156,624,900",796,Boomers
5,Albania,1987,female,75+ years,1,35600,2.81,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
6,Albania,1987,female,35-54 years,6,278800,2.15,Albania1987,NaN,"2,156,624,900",796,Silent
7,Albania,1987,female,25-34 years,4,257200,1.56,Albania1987,NaN,"2,156,624,900",796,Boomers
8,Albania,1987,male,55-74 years,1,137500,0.73,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
9,Albania,1987,female,5-14 years,0,311000,0.00,Albania1987,NaN,"2,156,624,900",796,Generation X
10,Albania,1987,female,55-74 years,0,144600,0.00,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
11,Albania,1987,male,5-14 years,0,338200,0.00,Albania1987,NaN,"2,156,624,900",796,Generation X
12,Albania,1988,female,75+ years,2,36400,5.49,Albania1988,NaN,"2,126,000,000",769,G.I. Generation
13,Albania,1988,male,15-24 years,17,319200,5.33,Albania1988,NaN,"2,126,000,000",769,Generation X
14,Albania,1988,male,75+ years,1,22300,4.48,Albania1988,NaN,"2,126,000,000",769,G.I. Generation
15,Albania,1988,male,35-54 years,14,314100,4.46,Albania1988,NaN,"2,126,000,000",769,Silent
16,Albania,1988,male,55-74 years,4,140200,2.85,Albania1988,NaN,"2,126,000,000",769,G.I. Generation
17,Albania,1988,female,15-24 years,8,295600,2.71,Albania1988,NaN,"2,126,000,000",769,Generation X
18,Albania,1988,female,55-74 years,3,147500,2.03,Albania1988,NaN,"2,126,000,000",769,G.I. Generation
19,Albania,1988,female,25-34 years,5,262400,1.91,Albania1988,NaN,"2,126,000,000",769,Boomers
20,Albania,1988,male,25-34 years,5,279900,1.79,Albania1988,NaN,"2,126,000,000",769,Boomers
21,Albania,1988,female,35-54 years,4,284500,1.41,Albania1988,NaN,"2,126,000,000",769,Silent
22,Albania,1988,female,5-14 years,0,317200,0.00,Albania1988,NaN,"2,126,000,000",769,Generation X
23,Albania,1988,male,5-14 years,0,345000,0.00,Albania1988,NaN,"2,126,000,000",769,Generation X
24,Albania,1989,male,75+ years,2,22500,8.89,Albania1989,NaN,"2,335,124,988",833,G.I. Generation
25,Albania,1989,male,25-34 years,18,283600,6.35,Albania1989,NaN,"2,335,124,988",833,Boomers
26,Albania,1989,male,35-54 years,15,318400,4.71,Albania1989,NaN,"2,335,124,988",833,Silent
27,Albania,1989,male,55-74 years,6,142100,4.22,Albania1989,NaN,"2,335,124,988",833,G.I. Generation
28,Albania,1989,male,15-24 years,12,323500,3.71,Albania1989,NaN,"2,335,124,988",833,Generation X
29,Albania,1989,female,35-54 years,7,288600,2.43,Albania1989,NaN,"2,335,124,988",833,Silent
...,...,...,...,...,...,...,...,...,...,...,...,...
27790,Uzbekistan,2012,female,25-34 years,148,2556673,5.79,Uzbekistan2012,0.668,"51,821,573,338",1964,Millenials
27791,Uzbekistan,2012,female,35-54 years,89,3474788,2.56,Uzbekistan2012,0.668,"51,821,573,338",1964,Generation X
27792,Uzbekistan,2012,male,5-14 years,67,2701361,2.48,Uzbekistan2012,0.668,"51,821,573,338",1964,Generation Z
27793,Uzbekistan,2012,female,55-74 years,25,1283060,1.95,Uzbekistan2012,0.668,"51,821,573,338",1964,Boomers
27794,Uzbekistan,2012,female,75+ years,4,338557,1.18,Uzbekistan2012,0.668,"51,821,573,338",1964,Silent
27795,Uzbekistan,2012,female,5-14 years,16,2578408,0.62,Uzbekistan2012,0.668,"51,821,573,338",1964,Generation Z
27796,Uzbekistan,2013,male,35-54 years,481,3346411,14.37,Uzbekistan2013,0.672,"57,690,453,461",2150,Generation X
27797,Uzbekistan,2013,male,25-34 years,328,2644648,12.40,Uzbekistan2013,0.672,"57,690,453,461",2150,Millenials
27798,Uzbekistan,2013,female,15-24 years,323,3039740,10.63,Uzbekistan2013,0.672,"57,690,453,461",2150,Millenials
27799,Uzbekistan,2013,male,15-24 years,320,3171202,10.09,Uzbekistan2013,0.672,"57,690,453,461",2150,Millenials
27800,Uzbekistan,2013,male,55-74 years,119,1202790,9.89,Uzbekistan2013,0.672,"57,690,453,461",2150,Boomers
27801,Uzbekistan,2013,male,75+ years,13,221002,5.88,Uzbekistan2013,0.672,"57,690,453,461",2150,Silent
27802,Uzbekistan,2013,female,25-34 years,146,2647820,5.51,Uzbekistan2013,0.672,"57,690,453,461",2150,Millenials
27803,Uzbekistan,2013,female,35-54 years,99,3547895,2.79,Uzbekistan2013,0.672,"57,690,453,461",2150,Generation X
27804,Uzbekistan,2013,female,75+ years,8,345180,2.32,Uzbekistan2013,0.672,"57,690,453,461",2150,Silent
27805,Uzbekistan,2013,male,5-14 years,61,2720938,2.24,Uzbekistan2013,0.672,"57,690,453,461",2150,Generation Z
27806,Uzbekistan,2013,female,55-74 years,21,1356298,1.55,Uzbekistan2013,0.672,"57,690,453,461",2150,Boomers
27807,Uzbekistan,2013,female,5-14 years,31,2595000,1.19,Uzbekistan2013,0.672,"57,690,453,461",2150,Generation Z
27808,Uzbekistan,2014,male,35-54 years,519,3421300,15.17,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation X
27809,Uzbekistan,2014,male,25-34 years,318,2739150,11.61,Uzbekistan2014,0.675,"63,067,077,179",2309,Millenials
27810,Uzbekistan,2014,female,15-24 years,347,2992817,11.59,Uzbekistan2014,0.675,"63,067,077,179",2309,Millenials
27811,Uzbekistan,2014,male,55-74 years,144,1271111,11.33,Uzbekistan2014,0.675,"63,067,077,179",2309,Boomers
27812,Uzbekistan,2014,male,15-24 years,347,3126905,11.10,Uzbekistan2014,0.675,"63,067,077,179",2309,Millenials
27813,Uzbekistan,2014,male,75+ years,17,224995,7.56,Uzbekistan2014,0.675,"63,067,077,179",2309,Silent
27814,Uzbekistan,2014,female,25-34 years,162,2735238,5.92,Uzbekistan2014,0.675,"63,067,077,179",2309,Millenials
27815,Uzbekistan,2014,female,35-54 years,107,3620833,2.96,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation X
27816,Uzbekistan,2014,female,75+ years,9,348465,2.58,Uzbekistan2014,0.675,"63,067,077,179",2309,Silent
27817,Uzbekistan,2014,male,5-14 years,60,2762158,2.17,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z
27818,Uzbekistan,2014,female,5-14 years,44,2631600,1.67,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z
27819,Uzbekistan,2014,female,55-74 years,21,1438935,1.46,Uzbekistan2014,0.675,"63,067,077,179",2309,Boomers

In [ ]:
# seperate features and targets
features = ["country", "year", "sex", "age", "suicides_no", "population"," suicides/100k_pop", "country_year",
            "HDI_for_year", "gdp_for_year", "gdp_per_capita", "generation"]

# targets = 

# print("features: ", features)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27820 entries, 0 to 27819
Data columns (total 12 columns):
country               27820 non-null object
year                  27820 non-null int64
sex                   27820 non-null object
age                   27820 non-null object
suicides_no           27820 non-null int64
population            27820 non-null int64
suicides/100k pop     27820 non-null float64
country-year          27820 non-null object
HDI for year          8364 non-null float64
 gdp_for_year ($)     27820 non-null object
gdp_per_capita ($)    27820 non-null int64
generation            27820 non-null object
dtypes: float64(2), int64(4), object(6)
memory usage: 2.5+ MB

In [9]:
df.describe()

,year,suicides_no,population,suicides/100k pop,HDI for year,gdp_per_capita ($)
count,27820.000000,27820.000000,2.782000e+04,27820.000000,8364.000000,27820.000000
mean,2001.258375,242.574407,1.844794e+06,12.816097,0.776601,16866.464414
std,8.469055,902.047917,3.911779e+06,18.961511,0.093367,18887.576472
min,1985.000000,0.000000,2.780000e+02,0.000000,0.483000,251.000000
25%,1995.000000,3.000000,9.749850e+04,0.920000,0.713000,3447.000000
50%,2002.000000,25.000000,4.301500e+05,5.990000,0.779000,9372.000000
75%,2008.000000,131.000000,1.486143e+06,16.620000,0.855000,24874.000000
max,2016.000000,22338.000000,4.380521e+07,224.970000,0.944000,126352.000000

Let's check for null values.

In [10]:
#number of missing values in the entire dataframe
print(df.isnull().values.sum())

#the column-wise distribution of missing values
print(df.isnull().sum())

19456
country                   0
year                      0
sex                       0
age                       0
suicides_no               0
population                0
suicides/100k pop         0
country-year              0
HDI for year          19456
 gdp_for_year ($)         0
gdp_per_capita ($)        0
generation                0
dtype: int64

There is only one feature where there are missing values, HDI for year. HDI, Human Development Index is a metric of measuring the . The United Nations releases a study every year on the HDI of every country. This feature may be a very meaniful metric of suicide detection.

0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
5          NaN
6          NaN
7          NaN
8          NaN
9          NaN
10         NaN
11         NaN
12         NaN
13         NaN
14         NaN
15         NaN
16         NaN
17         NaN
18         NaN
19         NaN
20         NaN
21         NaN
22         NaN
23         NaN
24         NaN
25         NaN
26         NaN
27         NaN
28         NaN
29         NaN
         ...
27790    0.668
27791    0.668
27792    0.668
27793    0.668
27794    0.668
27795    0.668
27796    0.672
27797    0.672
27798    0.672
27799    0.672
27800    0.672
27801    0.672
27802    0.672
27803    0.672
27804    0.672
27805    0.672
27806    0.672
27807    0.672
27808    0.675
27809    0.675
27810    0.675
27811    0.675
27812    0.675
27813    0.675
27814    0.675
27815    0.675
27816    0.675
27817    0.675
27818    0.675
27819    0.675
Name: HDI for year, Length: 27820, dtype: float64

We will also have to check for any duplicate values in the data.

In [15]:
for feature in features:
    print(df[feature].value_counts())

female    13910
male      13910
Name: sex, dtype: int64

Convert catagorical values to continous values.

In [ ]:
def to_binary(entry):
    if entry == "male" or entry == "Male":
        return 0
    if entry == "female" or entry == "Female":
        return 1
    return entry

df = df.applymap(to_binary)
df.head()